var pastebinTypes = {
  "javascript": "JavaScript",
  "asm": "ASM (NASM)",
  "c": "C",
  "csharp": "C#",
  "cpp": "C++",
  "css": "CSS",
  "dart": "Dart",
  "fortran": "Fortran",
  "gettext": "GetText",
  "go": "Go",
  "html5": "HTML 5",
  "java": "Java",
  "json": "JSON",
  "kixtart": "KiXtart",
  "kotlin": "Kotlin",
  "markdown": "Markdown",
  "matlab": "MatLab",
  "objc": "Objective C",
  "perl": "Perl",
  "plsql": "PL/SQL",
  "python": "Python",
  "ruby": "Ruby",
  "scala": "Scala",
  "sql": "SQL",
  "swift": "Swift",
  "typescript": "TypeScript",
  "xml": "XML",
  "yaml": "YAML",
  "latex": "Latex",
};
